SELECT PRODUCT_CODE, SUM(PRICE*SALES_AMOUNT) AS SALES
FROM PRODUCT P JOIN OFFLINE_SALE O ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE

















# SELECT PRODUCT_CODE, SUM(PRICE * SALES_AMOUNT) AS SALES
# FROM PRODUCT JOIN OFFLINE_SALE ON PRODUCT.PRODUCT_ID = OFFLINE_SALE.PRODUCT_ID
# GROUP BY PRODUCT_CODE
# ORDER BY SALES DESC, PRODUCT_CODE;